spring:
  datasource:
    url: jdbc:mysql://localhost:3306/querydslTune?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 500
        show_sql: true
        format_sql: true

decorator:
  datasource:
    p6spy:
      enable-logging: true